spring.profiles.active=${APP_PROFILE:dev}
spring.application.name=metical-converter
application.version=${APP_VERSION}
application.base.currency=${BASE_CURRENCY}


sentry.dsn=https://308c694bf53dc37733eeb6fb163f76a7@o4509329191600128.ingest.de.sentry.io/4509621674901584
# Add data like request headers and IP for users,
# see https://docs.sentry.io/platforms/java/guides/spring-boot/data-management/data-collected/ for more info
sentry.send-default-pii=true
